---
services:
  postgres:
    image: postgres:latest
    container_name: snack-postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - snack-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: snack-app
  #   environment:
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     DATABASE_PORT: 5432
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     JWT_SECRET: ${JWT_SECRET}
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - snack-network

networks:
  snack-network:
    driver: bridge
