---
services:
  postgres:
    image: postgres:latest
    container_name: snack-postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432  
    networks: [snack-network]
networks:
  snack-network:
    driver: bridge
